/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbmsproject_bankinggui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author SOUMIK
 */
public class Transfer extends javax.swing.JDialog {

    /**
     * Creates new form Transfer
     */
    Connection myconObj=null;
    Statement mystatObj=null;
    ResultSet myresObj=null;
    ResultSetMetaData mymetaObj=null;
    static boolean check=false;
    public Transfer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        src = new javax.swing.JTextField();
        dest = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        transfer = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transfer Funds");

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("First Account");

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setText("Second Account");

        dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        jLabel3.setText("Amount");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(src, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(dest)
                    .addComponent(jTextField1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(src, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        transfer.setBackground(new java.awt.Color(204, 204, 255));
        transfer.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        transfer.setText("Transfer");
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });

        close.setBackground(new java.awt.Color(204, 204, 255));
        close.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        close.setText("Cancel");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transfer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        // TODO add your handling code here:
        String sacc=src.getText();
        String dacc=dest.getText();
        String a=jTextField1.getText();
        if(sacc.equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(this,"Source Account field cannot be empty", "Error",JOptionPane.ERROR_MESSAGE);
        else if(dacc.equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(this,"Destination Account field cannot be empty", "Error",JOptionPane.ERROR_MESSAGE);
        else if(a.equalsIgnoreCase(""))
            JOptionPane.showMessageDialog(this,"Amount field cannot be empty", "Error",JOptionPane.ERROR_MESSAGE);
        else if(sacc.equalsIgnoreCase(dacc))
        {
            //joptionpane;
            JOptionPane.showMessageDialog(this,"Source and Destination accounts cannot be same", "Error",JOptionPane.ERROR_MESSAGE);
            //this.dispose();
            
        }
        else
        {
        
        double amount=Double.parseDouble(a);
        
        try
        {
            myconObj=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject_banking","root","whocares");
            mystatObj=myconObj.createStatement();
            String query="select * from accounts where ano='"+sacc+"'and cno='"+DBMSProject_BankingGUI.cmno+"'";
            myresObj=mystatObj.executeQuery(query);
            myresObj.next();
            double osbal,odbal,nsbal,ndbal;
            osbal=myresObj.getDouble("bal");
            if(amount>osbal)
                JOptionPane.showMessageDialog(this,"Amount to be transferred exceeds Account Balance : "+osbal+".", "Error",JOptionPane.ERROR_MESSAGE);
            else
            {
            check=true;
            System.out.println(osbal);
            query="select * from accounts where ano='"+dacc+"'";
            myresObj=mystatObj.executeQuery(query);
            myresObj.next();
            odbal=myresObj.getDouble("bal");
            System.out.println(odbal);
            
            nsbal=osbal-amount;
            ndbal=odbal+amount;
            
            query="update dbmsproject_banking.accounts set bal="+nsbal+" where ano='"+sacc+"'";
            mystatObj.executeUpdate(query);
            query="update dbmsproject_banking.accounts set bal="+ndbal+" where ano='"+dacc+"'";
            mystatObj.executeUpdate(query);
            
            
            query="select * from transactions";
            myresObj=mystatObj.executeQuery(query);
            while(myresObj.next());
            myresObj.previous();
            String tid=myresObj.getString("tid");
            String prefix="TXN";
            String num=tid.substring(3);
            long numb=Long.parseLong(num);
            long numb2;
            numb++;
            numb2=numb+1;
            num=Long.toString(numb);
            String num2=Long.toString(numb2);
            String ntid=prefix+num;
            String ntid2=prefix+num2;
            
            Date date = new Date();
            LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int td=localDate.getDayOfMonth();
            int tm=localDate.getMonthValue();
            int ty=localDate.getYear();
            String d=Integer.toString(td);
            String m=Integer.toString(tm);
            String y=Integer.toString(ty);
            
            String mode="Transfer";
            String type2="Credit";
            String type1="Debit";
            
            query="Insert into dbmsproject_banking.transactions values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement p1=myconObj.prepareStatement(query);
            p1.setString(1,ntid);
            p1.setString(2,d);
            p1.setString(3,m);
            p1.setString(4,y);
            p1.setString(5,sacc);
            p1.setDouble(6,amount);
            p1.setDouble(7,osbal);
            p1.setDouble(8,nsbal);
            p1.setString(9,type1);
            p1.setString(10,mode);
            p1.executeUpdate();
            
            query="Insert into dbmsproject_banking.transactions values(?,?,?,?,?,?,?,?,?,?)";
            PreparedStatement p2=myconObj.prepareStatement(query);
            p2.setString(1,ntid2);
            p2.setString(2,d);
            p2.setString(3,m);
            p2.setString(4,y);
            p2.setString(5,dacc);
            p2.setDouble(6,amount);
            p2.setDouble(7,odbal);
            p2.setDouble(8,ndbal);
            p2.setString(9,type2);
            p2.setString(10,mode);
            p2.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Transfer Successful", "Success",JOptionPane.PLAIN_MESSAGE);
            }
        }
        catch(SQLException e)
        {
            //e.printStackTrace();
            boolean err1=false;
            try
            {
                myconObj=DriverManager.getConnection("jdbc:mysql://localhost:3306/dbmsproject_banking","root","whocares");
                mystatObj=myconObj.createStatement();
                String query="select count(*) from accounts where ano='"+sacc+"'";
                myresObj=mystatObj.executeQuery(query);
                myresObj.next();
                int c=myresObj.getInt(1);
                System.out.println("P="+check);
                if(check==false)
                {
                    err1=true;
                    JOptionPane.showMessageDialog(this,"Transaction Failed. Source Account must be one of your accounts.", "Error",JOptionPane.ERROR_MESSAGE);
                }
            }
            catch(SQLException e1)
            {
                err1=true;
                JOptionPane.showMessageDialog(this,"Transaction Failed. Invalid Source or Destination Accounts or Amount.", "Error",JOptionPane.ERROR_MESSAGE);
            }
            if(!err1)
            {
                JOptionPane.showMessageDialog(this,"Transaction Failed. Invalid Source or Destination Accounts or Amount.", "Error",JOptionPane.ERROR_MESSAGE);
            }
        }   
        }
    }//GEN-LAST:event_transferActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Transfer dialog = new Transfer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JTextField dest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField src;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables
}
